[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ridias", email = "ridias@student.42lisboa.com" }
]
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.14.0",
    "llm-sdk>=1.0.1",
    "numpy>=2.2.6",
    "pydantic>=2.13.4",
    "torch>=2.13.0",
    "uv>=0.12.3",
]

[project.scripts]
call-me-maybe = "call_me_maybe:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
